{
  "openapi": "3.0.0",
  "info": {
    "title": "Zuriportfolio Shop API",
    "description": "Zuriportfolio shop internal / external api.",
    "version": "0.1.9"
  },
  "servers": [
    {
      "url": "http://localhost:8080/api",
      "description": "Zuriportfolio shop internal / external api."
    },
    {
      "url": "https://zuriportfolio-shop-internal-api.onrender.com/api",
      "description": "Production server"
    },
    {
      "url": "https://auth.akuya.tech/api",
      "description": "Authentication server"
    }
  ],
  "paths": {
    "/products": {
      "get": {
        "tags": [
          "Product"
        ],
        "summary": "Fetch all products",
        "description": "",
        "parameters": [
          {
            "name": "productname",
            "in": "query",
            "description": "Use to search for product by name",
            "required": false,
            "explode": true,
            "schema": {
              "type": "string"
            }
          }
        ],
        "responses": {
          "200": {
            "description": "successful operation",
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "#/components/schemas/GetProduct"
                }
              }
            }
          }
        },
        "security": [
          {
            "BearerAuth": []
          }
        ]
      }
    },
    "/products/marketplace": {
      "get": {
        "tags": [
          "Product"
        ],
        "summary": "Fetch all marketplace products",
        "description": "",
        "responses": {
          "200": {
            "description": "successful operation",
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "#/components/schemas/GetProduct"
                }
              }
            }
          }
        }
      }
    },
    "/product/add": {
      "post": {
        "tags": [
          "Product"
        ],
        "summary": "Create a new Product",
        "description": "",
        "requestBody": {
          "content": {
            "multipart/form-data": {
              "schema": {
                "$ref": "#/components/schemas/AddProduct"
              }
            }
          }
        },
        "responses": {
          "200": {
            "description": "successful operation",
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "#/components/schemas/AddProduct"
                }
              }
            }
          }
        },
        "security": [
          {
            "BearerAuth": []
          }
        ]
      }
    },
    "/product/{product_id}": {
      "get": {
        "tags": [
          "Product"
        ],
        "summary": "Fetch product by id",
        "description": "",
        "parameters": [
          {
            "name": "product_id",
            "in": "path",
            "description": "Product id",
            "required": true,
            "schema": {
              "type": "string"
            }
          }
        ],
        "responses": {
          "200": {
            "description": "successful operation",
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "#/components/schemas/GetProduct"
                }
              }
            }
          }
        }
      },
      "delete": {
        "tags": [
          "Product"
        ],
        "summary": "Delete a product",
        "description": "Delete a specific product.",
        "parameters": [
          {
            "name": "product_id",
            "in": "path",
            "description": "Product id",
            "required": true,
            "schema": {
              "type": "string"
            }
          }
        ],
        "responses": {
          "200": {
            "description": "Action authorized successfully."
          },
          "400": {
            "description": "Bad request. Please check the request parameters."
          },
          "401": {
            "description": "Unauthorized. Token is invalid or action is not permitted."
          },
          "500": {
            "description": "Internal server error."
          }
        },
        "security": [
          {
            "BearerAuth": []
          }
        ]
      }
    },
    "/order/status/{order_id}": {
      "patch": {
        "tags": [
          "Order"
        ],
        "summary": "Update Order Status",
        "description": "Update the status of a specific order.",
        "parameters": [
          {
            "name": "order_id",
            "in": "path",
            "description": "Order ID",
            "required": true,
            "schema": {
              "type": "string"
            }
          }
        ],
        "requestBody": {
          "content": {
            "application/json": {
              "schema": {
                "type": "object",
                "properties": {
                  "status": {
                    "type": "string",
                    "enum": [
                      "pending",
                      "complete",
                      "failed"
                    ],
                    "example": "complete"
                  }
                },
                "required": [
                  "status"
                ]
              }
            }
          }
        },
        "responses": {
          "200": {
            "description": "Order status updated successfully."
          },
          "400": {
            "description": "Bad request. Please check the request parameters or status value."
          },
          "401": {
            "description": "Unauthorized. Token is invalid or action is not permitted."
          },
          "404": {
            "description": "Order not found."
          },
          "500": {
            "description": "Internal server error."
          }
        },
        "security": [
          {
            "BearerAuth": []
          }
        ]
      }
    },
    "/orders": {
      "get": {
        "tags": [
          "Order"
        ],
        "summary": "Gets all order count withing a timeframe",
        "description": "Gets all order count withing a timeframe",
        "parameters": [
          {
            "name": "timeframe",
            "in": "query",
            "description": " values: today, yesterday,one-week-ago and two-weeks-ago ",
            "required": "true",
            "type": "string"
          }
        ],
        "responses": {
          "200": {
            "description": "successful operation",
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "#/components/schemas/ordersCount"
                }
              }
            }
          }
        },
        "security": [
          {
            "BearerAuth": []
          }
        ]
      }
    },
    "/product/category": {
      "post": {
        "tags": [
          "Product"
        ],
        "summary": "Create a product category",
        "description": "Create a parent or subcategory.",
        "requestBody": {
          "content": {
            "application/json": {
              "schema": {
                "$ref": "#/components/schemas/CreateCategory"
              },
              "example": {
                "name": "Software Enginering",
                "parent_id": null
              }
            }
          }
        },
        "responses": {
          "201": {
            "description": "Category created successfully.",
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "#/components/schemas/CategoryResponse"
                },
                "example": {
                  "parentCategory": {
                    "$ref": "#/components/schemas/ProductCategory"
                  },
                  "subCategory": {
                    "$ref": "#/components/schemas/ProductSubCategory"
                  }
                }
              }
            }
          },
          "400": {
            "description": "Bad request. Please check the request parameters or status value."
          },
          "401": {
            "description": "Unauthorized. Token is invalid or action is not permitted."
          },
          "404": {
            "description": "Order not found."
          },
          "500": {
            "description": "Internal server error."
          }
        },
        "security": [
          {
            "BearerAuth": []
          }
        ]
      }
    },
    "/discount": {
      "post": {
        "summary": "Create a discount",
        "tags": [
          "Discount"
        ],
        "requestBody": {
          "description": "Discount data",
          "required": true,
          "content": {
            "application/json": {
              "schema": {
                "type": "object",
                "properties": {
                  "discount_type": {
                    "type": "string",
                    "description": "Type of discount",
                    "required": true
                  },
                  "amount": {
                    "type": "number",
                    "description": "Discount amount",
                    "required": true
                  },
                  "quantity": {
                    "type": "number",
                    "description": "Minimum quantity for the discount",
                    "minimum": 1,
                    "required": true
                  },
                  "maximum_discount_price": {
                    "type": "number",
                    "description": "Maximum discount price",
                    "required": false
                  },
                  "product_ids": {
                    "type": "array",
                    "items": {
                      "type": "string",
                      "description": "Product ID with a custom UUID pattern",
                      "pattern": "^[0-9a-fA-F]{8}-[0-9a-fA-F]{4}-[0-9a-fA-F]{4}-[0-9a-fA-F]{4}-[0-9a-fA-F]{12}$",
                      "example": "valid-uuid",
                      "required": true
                    },
                    "description": "Array of product IDs",
                    "required": true
                  },
                  "valid_from": {
                    "type": "string",
                    "format": "date-time",
                    "description": "Start date and time of discount",
                    "required": true
                  },
                  "valid_to": {
                    "type": "string",
                    "format": "date-time",
                    "description": "End date and time of discount",
                    "required": true
                  }
                }
              }
            }
          },
          "security": [
            {
              "BearerAuth": []
            }
          ]
        },
        "responses": {
          "201": {
            "description": "Discount created successfully"
          },
          "400": {
            "description": "Bad request"
          }
        }
      }
    },
    "/discount/promotions": {
      "get": {
        "summary": "Retrieve Products with Promotions and number of sales",
        "tags": [
          "Discount"
        ],
        "security": [
          {
            "BearerAuth": []
          }
        ],
        "parameters": [
          {
            "name": "page",
            "in": "query",
            "description": "Page number for pagination (default: 1)",
            "required": false,
            "schema": {
              "type": "integer"
            }
          },
          {
            "name": "itemsPerPage",
            "in": "query",
            "description": "Number of items per page (default: 10)",
            "required": false,
            "schema": {
              "type": "integer"
            }
          }
        ],
        "responses": {
          "200": {
            "description": "List of products with associated promotions and tracked promotions",
            "content": {
              "application/json": {
                "example": [
                  {
                    "product": {
                      "id": "product1",
                      "name": "Product A"
                    },
                    "promo": {
                      "id": "promo1",
                      "discount_type": "Percentage",
                      "quantity": 5,
                      "amount": 10.0,
                      "valid_from": "2023-10-15T00:00:00Z",
                      "valid_to": "2023-10-30T00:00:00Z"
                    },
                    "sales": 2
                  },
                  {
                    "product": {
                      "id": "product2",
                      "name": "Product B"
                    },
                    "promo": {
                      "id": "promo2",
                      "discount_type": "Fixed",
                      "quantity": 10,
                      "amount": 50.0,
                      "valid_from": "2023-11-01T00:00:00Z",
                      "valid_to": "2023-11-15T00:00:00Z"
                    },
                    " sales": 1
                  }
                ]
              }
            }
          },
          "401": {
            "description": "Unauthorized access"
          },
          "404": {
            "description": "User not found"
          }
        }
      }
    },
    "/shop": {
      "post": {
        "summary": "Create a shop",
        "tags": [
          "Shop"
        ],
        "requestBody": {
          "description": "Shop data",
          "required": true,
          "content": {
            "application/json": {
              "schema": {
                "type": "object",
                "properties": {
                  "name": {
                    "type": "string",
                    "description": "shop name",
                    "required": true
                  }
                }
              }
            }
          },
          "security": [
            {
              "BearerAuth": []
            }
          ]
        },
        "responses": {
          "201": {
            "description": "Shop created successfully"
          },
          "400": {
            "description": "Bad request"
          }
        }
      }
    },
    "/shops": {
      "get": {
        "tags": [
          "Shops"
        ],
        "summary": "Fetch all shops",
        "description": "",
        "responses": {
          "200": {
            "description": "successful operation",
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "#/components/schemas/shops"
                }
              }
            }
          }
        },
        "security": [
          {
            "BearerAuth": []
          }
        ]
      }
    },
    "/shop/store-traffic": {
      "post": {
        "summary": "Used to track user visit to a shop",
        "tags": [
          "Shop"
        ],
        "requestBody": {
          "description": "Shop data",
          "required": true,
          "content": {
            "application/json": {
              "schema": {
                "type": "object",
                "properties": {
                  "shop_id": {
                    "type": "string",
                    "description": "The shop id of the shop visited",
                    "required": true
                  }
                }
              }
            }
          }
        },
        "responses": {
          "200": {
            "description": "Traffic added"
          },
          "400": {
            "description": "Bad request"
          }
        }
      }
    },
    "/product/categories": {
      "get": {
        "summary": "Retrieve Product Categories",
        "description": "Get a list of all product categories along with their subcategories.",
        "responses": {
          "200": {
            "description": "Successful response",
            "content": {
              "application/json": {
                "example": [
                  {
                    "id": 11,
                    "name": "Electronics",
                    "product_id": "11",
                    "createdAt": "2023-10-11T21:25:23.0000Z",
                    "sub_categories": [
                      {
                        "id": 101,
                        "name": "Smartphones",
                        "parent_category_id": 1011,
                        "createdAt": "2023-10-11T21:25:23.0000Z"
                      }
                    ]
                  }
                ]
              }
            }
          }
        }
      }
    },
    "/sales/reports": {
      "get": {
        "tags": [
          "Sales"
        ],
        "summary": "Retrieve Sales Reports",
        "description": "Get sales reports based on timeframes.",
        "parameters": [
          {
            "name": "timeframe",
            "in": "query",
            "description": "Comma-separated list of timeframes (e.g., 12m,3m,1yr,7d,24hr)",
            "required": true,
            "schema": {
              "type": "string"
            }
          }
        ],
        "responses": {
          "200": {
            "description": "Successful response",
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "#/components/schemas/SalesReport"
                }
              }
            }
          },
          "400": {
            "description": "Bad request"
          },
          "401": {
            "description": "Unauthorized"
          },
          "500": {
            "description": "Internal server error"
          }
        },
        "security": [
          {
            "BearerAuth": []
          }
        ]
      }
    },
    "/Orders/all": {
      "get": {
        "tags": [
          "Orders"
        ],
        "summary": "get all orders",
        "description": "To get All orders",
        "responses": {
          "200": {
            "description": "successful operation",
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "#/components/schemas/getOrderData"
                },
                "example": [
                  {
                    "order_id": "1122",
                    "order_price": 12.22,
                    "createdAt": "2023-10-11T18:00:52.000Z",
                    "merchant": {
                      "revenue": [
                        {
                          "amount": 3000.5
                        }
                      ],
                      "customer_orders": [
                        {
                          "status": "complete",
                          "sales_report": [
                            {
                              "sales": 11
                            }
                          ]
                        }
                      ],
                      "customer": [
                        {
                          "username": "Customer1"
                        }
                      ],
                      "product": {
                        "price": 12.34,
                        "name": "Longchair",
                        "categories": [
                          {
                            "name": "Software"
                          }
                        ]
                      }
                    }
                  }
                ]
              }
            }
          },
          "401": {
            "description": "Unauthorized. Please provide an authenticated user."
          },
          "403": {
            "description": "Forbidden. Token is invalid or action is not permitted for provided user."
          },
          "500": {
            "description": "Internal server error."
          }
        }
      },
      "/auth/send-verification": {
        "post": {
          "tags": [
            "Authentication"
          ],
          "summary": "Send Verification Code",
          "description": "Sends a verification code to the user's email for account activation.",
          "requestBody": {
            "content": {
              "application/json": {
                "schema": {
                  "type": "object",
                  "properties": {
                    "first_name": {
                      "type": "string",
                      "example": "John"
                    },
                    "last_name": {
                      "type": "string",
                      "example": "Doe"
                    },
                    "username": {
                      "type": "string",
                      "example": "johndoe"
                    },
                    "email": {
                      "type": "string",
                      "format": "email",
                      "example": "sicoj92691@elixirsd.com"
                    },
                    "password": {
                      "type": "string",
                      "format": "password",
                      "example": "myPassword2021"
                    },
                    "refresh_token": {
                      "type": "string",
                      "format": "uuid",
                      "example": "42e2a46a-e56f-4e4d-be0e-0675b7026f58"
                    }
                  },
                  "required": [
                    "first_name",
                    "last_name",
                    "username",
                    "email",
                    "password",
                    "refresh_token"
                  ]
                }
              }
            }
          },
          "responses": {
            "200": {
              "description": "Verification code sent successfully."
            },
            "400": {
              "description": "Bad request. Please check the request parameters."
            },
            "401": {
              "description": "Unauthorized. Refresh token is invalid or has expired."
            },
            "500": {
              "description": "Internal server error."
            }
          }
        }
      },
      "/auth/confirm-verification": {
        "post": {
          "tags": [
            "Authentication"
          ],
          "summary": "Confirm Verification Code",
          "description": "Verifies the verification code against the stored code for the user in the database.",
          "requestBody": {
            "content": {
              "application/json": {
                "schema": {
                  "type": "object",
                  "properties": {
                    "email": {
                      "type": "string",
                      "format": "email",
                      "example": "sicoj92691@elixirsd.com"
                    },
                    "verificationCode": {
                      "type": "string",
                      "example": "3903"
                    }
                  },
                  "required": [
                    "email",
                    "verificationCode"
                  ]
                }
              }
            }
          },
          "responses": {
            "200": {
              "description": "Verification code confirmed successfully."
            },
            "400": {
              "description": "Bad request. Please check the request parameters."
            },
            "401": {
              "description": "Unauthorized. Verification code is invalid or has expired."
            },
            "500": {
              "description": "Internal server error."
            }
          }
        }
      },
      "/order/status/{order_id}": {
        "patch": {
          "tags": [
            "Order"
          ],
          "summary": "Update Order Status",
          "description": "Update the status of a specific order.",
          "parameters": [
            {
              "name": "order_id",
              "in": "path",
              "description": "Order ID",
              "required": true,
              "schema": {
                "type": "string"
              }
            }
          ],
          "requestBody": {
            "content": {
              "application/json": {
                "schema": {
                  "type": "object",
                  "properties": {
                    "status": {
                      "type": "string",
                      "enum": [
                        "pending",
                        "complete",
                        "failed"
                      ],
                      "example": "complete"
                    }
                  },
                  "required": [
                    "status"
                  ]
                }
              }
            }
          },
          "responses": {
            "200": {
              "description": "Order status updated successfully."
            },
            "400": {
              "description": "Bad request. Please check the request parameters or status value."
            },
            "401": {
              "description": "Unauthorized. Token is invalid or action is not permitted."
            },
            "404": {
              "description": "Order not found."
            },
            "500": {
              "description": "Internal server error."
            }
          },
          "security": [
            {
              "BearerAuth": []
            }
          ]
        }
      }
    },
    "/orders/average": {
      "get": {
        "tags": [
          "Orders"
        ],
        "summary": "Fetch the average order value for today",
        "parameters": [
          {
            "name": "timeframe",
            "in": "query",
            "description": "Timeframe for calculating the average order value. Should be 'today'.",
            "required": true,
            "schema": {
              "type": "string",
              "enum": [
                "today"
              ],
              "example": "today"
            }
          }
        ],
        "responses": {
          "200": {
            "description": "Successful operation",
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "#/components/schemas/AverageOrderValue"
                }
              }
            }
          },
          "400": {
            "description": "Bad request. Please check the request parameters."
          },
          "401": {
            "description": "Unauthorized. Token is invalid or action is not permitted."
          },
          "500": {
            "description": "Internal server error."
          }
        },
        "security": [
          {
            "BearerAuth": []
          }
        ]
      }
    },
    "/orders/search/{name}": {
      "get": {
        "tags": [
          "Orders"
        ],
        "summary": "Search Order By Product Name",
        "description": "",
        "parameters": [
          {
            "name": "name",
            "in": "path",
            "description": "Product name",
            "required": true,
            "schema": {
              "type": "string"
            }
          }
        ],
        "responses": {
          "200": {
            "description": "successful operation",
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "#/components/schemas/searchOrder"
                },
                "example": {
                  "totalResults": 2,
                  "orders": [
                    {
                      "order_id": "1122",
                      "order_price": 12.22,
                      "createdAt": "2023-10-11T18:00:52.000Z",
                      "merchant": {
                        "revenue": [
                          {
                            "amount": 3000.5
                          }
                        ],
                        "customer_orders": [
                          {
                            "status": "complete",
                            "sales_report": [
                              {
                                "sales": 11
                              }
                            ]
                          }
                        ],
                        "customer": [
                          {
                            "username": "Customer1"
                          }
                        ],
                        "product": {
                          "price": 12.34,
                          "name": "Longchair",
                          "categories": [
                            {
                              "name": "Software"
                            }
                          ]
                        }
                      }
                    }
                  ]
                }
              }
            }
          },
          "401": {
            "description": "Unauthorized. Please provide an authenticated user."
          },
          "403": {
            "description": "Forbidden. Token is invalid or action is not permitted for provided user."
          },
          "500": {
            "description": "Internal server error."
          }
        },
        "security": [
          {
            "BearerAuth": []
          }
        ]
      }
    },

    "/revenue/{order_id}": {
      "patch": {
        "tags": ["Revenue"],
        "summary": "Update Revenue",
        "description": "Update the revenue based on the order's status",
        "parameters": [
          {
            "name": "order_id",
            "in": "path",
            "required": true,
            "schema": {
              "type": "string",
              "format": "string"
            },
            "description": "ID of the order to update revenue for"
          }
        ],
        "responses": {
          "200": {
            "description": "Successful operation",
            "content": {
              "application/json": {
                "example": {
                  "message": "Revenue updated successfully",
                  "data": {
                    "id": 1,
                    "user_id": "d7955c27-4d61-4cd6-a6bb-e6402151d51f",
                    "amount": 1500.0
                  }
                }
              }
            }
          },
          "400": {
            "description": "Bad request",
            "content": {
              "application/json": {
                "example": {
                  "error": "--order/not-found",
                  "message": "Order not found"
                }
              }
            }
          }
        }
      }
    },
    "/revenues": {
      "get": {
        "tags": ["Revenue"],
        "summary": "Get Revenue for Today",
        "description": "Get revenue data for today.",
        "parameters": [
          {
            "name": "timeframe",
            "in": "query",
            "description": "Timeframe for calculating revenue (e.g., today)",
            "required": true,
            "schema": {
              "type": "string",
              "enum": ["today"],
              "example": "today"
            }
          }
        ],
        "responses": {
          "200": {
            "description": "Revenue fetched successfully"
          },
          "400": {
            "description": "Missing parameter timeframe"
          },
          "401": {
            "description": "Unauthorized. Token is invalid or action is not permitted."
          }
        },
        "security": [
          {
            "BearerAuth": []
          }
        ]
      }
    }
  },

  "components": {
    "schemas": {
      "AddProduct": {
        "type": "object",
        "properties": {
          "image": {
            "type": "string",
            "format": "binary"
          },
          "name": {
            "type": "string"
          },
          "description": {
            "type": "string"
          },
          "quantity": {
            "type": "integer"
          },
          "categoryId": {
            "type": "integer"
          },
          "price": {
            "type": "number"
          },
          "discountPrice": {
            "type": "number"
          },
          "tax": {
            "type": "number"
          },
          "currency": {
            "type": "string"
          }
        },
        "required": [
          "image",
          "name",
          "description",
          "quantity",
          "categoryId",
          "price",
          "discountPrice",
          "tax",
          "currency"
        ],
        "example": {
          "categoryId": 1,
          "name": "HNGX polo",
          "description": "Red",
          "quantity": 4,
          "price": 500,
          "discount_price": 455,
          "tax": 2.2,
          "currency": "USD"
        }
      },
      "UpdateProductData": {
        "type": "object",
        "properties": {
          "newData": {
            "type": "object",
            "properties": {
              "name": {
                "type": "string",
                "required": true
              },
              "description": {
                "type": "string",
                "required": true
              },
              "quantity": {
                "type": "integer",
                "required": true
              },
              "categoryId": {
                "type": "integer",
                "required": true
              },
              "price": {
                "type": "number",
                "required": true
              },
              "discountPrice": {
                "type": "number",
                "required": true
              },
              "tax": {
                "type": "number",
                "required": true
              },
              "currency": {
                "type": "string",
                "required": true
              },
              "adminStatus": {
                "type": "string",
                "enum": [
                  "pending",
                  "review",
                  "approved",
                  "blacklist"
                ],
                "required": true
              }
            }
          }
        },
        "example": {
          "user_id": "d7955c27-4d61-4cd6-a6bb-e6402151d51f",
          "newData": {
            "name": "Nike Wears",
            "description": "Comfortable and beautifully Designed",
            "quantity": 53,
            "price": 5000,
            "discountPrice": 4500,
            "tax": 200,
            "currency": "Naira",
            "categoryId": 1,
            "adminStatus": "approved"
          }
        }
      },
      "UpdateProduct": {
        "type": "object",
        "properties": {
          "userId": {
            "type": "string"
          },
          "newData": {
            "$ref": "#/components/schemas/UpdateProductData"
          }
        },
        "required": [
          "userId"
        ],
        "example": {
          "user_id": "d7955c27-4d61-4cd6-a6bb-e6402151d51f",
          "newData": {
            "name": "Nike Wears",
            "description": "Comfortable and beautifully Designed",
            "quantity": 53,
            "price": 5000,
            "discountPrice": 4500,
            "tax": 200,
            "currency": "Naira",
            "categoryId": 1,
            "adminStatus": "approved"
          }
        }
      },
      "UpdateProductWithImage": {
        "type": "object",
        "properties": {
          "image": {
            "type": "array"
          },
          "userId": {
            "type": "string"
          },
          "newData": {
            "$ref": "#/components/schemas/UpdateProductData"
          }
        }
      },
      "GetProduct": {
        "type": "object",
        "properties": {}
      },
      "ordersCount": {
        "type": "number"
      },
      "CreateCategory": {
        "type": "object",
        "properties": {
          "parent_id": {
            "type": [
              "integer",
              "null",
              "undefined",
              ""
            ]
          },
          "name": {
            "type": "string"
          }
        },
        "required": [
          "name"
        ]
      },
      "ProductCategory": {
        "type": "object",
        "properties": {
          "id": {
            "type": "string"
          },
          "name": {
            "type": "string"
          },
          "user": {
            "type": "string"
          },
          "createdAt": {
            "type": "string",
            "format": "date-time"
          }
        }
      },
      "ProductSubCategory": {
        "type": "object",
        "properties": {
          "id": {
            "type": "string"
          },
          "name": {
            "type": "string"
          },
          "parentCategory": {
            "type": "string"
          },
          "createdAt": {
            "type": "string",
            "format": "date-time"
          }
        }
      },
      "CategoryResponse": {
        "type": "object",
        "properties": {
          "parentCategory": {
            "$ref": "#/components/schemas/ProductCategory"
          },
          "subCategory": {
            "$ref": "#/components/schemas/ProductSubCategory"
          },
          "name": {
            "$ref": "#/components/schemas/CreateCategory/properties/name"
          }
        }
      },
      "SalesReport": {
        "type": "object",
        "properties": {
          "id": {
            "type": "string"
          },
          "user_id": {
            "type": "string"
          },
          "sales": {
            "type": "integer"
          },
          "order_id": {
            "type": "string"
          },
          "createdAt": {
            "type": "string",
            "format": "date-time"
          }
        },
        "required": [
          "id",
          "user_id",
          "sales",
          "order_id",
          "createdAt"
        ]
      },
      "AddSales Report": {
        "type": "object",
        "properties": {
          "user_id": {
            "type": "string"
          },
          "order_id": {
            "type": "string"
          },
          "sales": {
            "type": "number"
          }
        },
        "required": [
          "user_id",
          "order_id",
          "sales"
        ],
        "example": {
          "user_id": "fecfd17b-51a3-4288-9bd0-77ac4b7d60a0",
          "order_id": "f47ac10b-58cc-4372-a567-0e02b2c3d479",
          "sales": 500
        }
      },
      "getOrderData": {
        "type": "object",
        "properties": {
          "order_id": {
            "type": "string"
          },
          "order_price": {
            "type": "number",
            "format": "float"
          },
          "createdAt": {
            "type": "string",
            "format": "date-time"
          },
          "merchant": {
            "type": "object",
            "properties": {
              "status": {
                "type": "string"
              }
            }
          },
          "customer": {
            "type": "object",
            "properties": {
              "username": {
                "type": "string"
              }
            }
          },
          "product": {
            "type": "object",
            "properties": {
              "name": {
                "type": "string"
              }
            }
          }
        },
        "required": [
          "order_id",
          "createdAt",
          "merchant",
          "customer",
          "product"
        ]
      },
      "AverageOrderValue": {
        "type": "object",
        "properties": {
          "averageSales": {
            "type": "number",
            "format": "double",
            "description": "The average order value for today."
          }
        },
        "example": {
          "averageSales": 50.45
        }
      },
      "searchOrder": {
        "type": "object",
        "properties": {
          "order_id": {
            "type": "string"
          },
          "order_price": {
            "type": "number",
            "format": "float"
          },
          "createdAt": {
            "type": "string",
            "format": "date-time"
          },
          "merchant": {
            "$ref": "#/components/schemas/MerchantData"
          }
        },
        "required": [
          "order_id",
          "order_price",
          "createdAt",
          "merchant"
        ]
      },
      "MerchantData": {
        "type": "object",
        "properties": {
          "revenue": {
            "$ref": "#/components/schemas/RevenueData",
            "customer_orders": {
              "$ref": "#/components/schemas/CustomerOrders",
              "type": "object",
              "properties": {
                "status": {
                  "type": "string"
                }
              }
            },
            "customer": {
              "type": "object",
              "properties": {
                "username": {
                  "type": "string"
                }
              }
            },
            "product": {
              "type": "object",
              "properties": {
                "name": {
                  "type": "string"
                }
              }
            }
          }
        },
        "required": [
          "order_id",
          "createdAt",
          "merchant",
          "customer",
          "product"
        ]
      },
      "RevenueData": {
        "type": "object",
        "properties": {
          "amount": {
            "type": "number"
          }
        }
      },
      "CustomerOrders": {
        "type": "object",
        "properties": {
          "status": {
            "type": "string"
          },
          "sales_report": {
            "$ref": "#/components/schemas/SalesData"
          }
        }
      },
      "SalesData": {
        "type": "object",
        "properties": {
          "sales": {
            "type": "number"
          }
        }
      },
      "CustomerData": {
        "type": "object",
        "properties": {
          "username": {
            "type": "string"
          }
        }
      },
      "ProductData": {
        "type": "object",
        "properties": {
          "price": {
            "type": "number"
          },
          "name": {
            "type": "string"
          },
          "categories": {
            "$ref": "#/components/schemas/CategoriesData"
          }
        }
      },
      "CategoriesData": {
        "type": "object",
        "properties": {
          "name": {
            "type": "string"
          }
        }
      }
    },
    "securitySchemes": {
      "BearerAuth": {
        "type": "http",
        "scheme": "bearer",
        "bearerFormat": "JWT"
      }
    }
  }
}